#pragma once

#include QMK_KEYBOARD_H

#include "features/layer_lock.h"
#include "microhacks.c"

// # BASE LAYER

#define QW18_BASE_L1    KC_Q, LCTL_T(KC_W), LALT_T(KC_E), LSFT_T(KC_R), KC_T
#define QW18_BASE_L2    KC_A, LT(2,KC_S), LT(1,KC_D), LT(3,KC_F), LSFT_T(KC_G)
#define QW18_BASE_L3    KC_Z, KC_X, KC_C, KC_V, KC_B
#define QW18_BASE_LT    KC_CCCV, OSM(MOD_LGUI), MEH_T(KC_SPACE)

#define QW18_BASE_R1    KC_Y, RGUI_T(KC_U), RALT_T(KC_I), RCTL_T(KC_O), KC_BSPC
#define QW18_BASE_R2    KC_H, LT(3,KC_J), LT(1,KC_K), LT(2,KC_L), KC_P
#define QW18_BASE_R3    KC_N, KC_M, KC_COMM, KC_DOT, KC_SLASH
#define QW18_BASE_RT    OSM(MOD_LSFT), KC_F19, CW_TOGG

// ###### Layer Symbols

#define QW18_SYM_L1 KC_NO, KC_CIRC, KC_AMPR, KC_TILD, KC_NO
#define QW18_SYM_L2 KC_NO, KC_GRAVE, KC_DQUO, KC_QUOT, KC_NO
#define QW18_SYM_L3 KC_NO, KC_BSLS, KC_UNDS, KC_PIPE, KC_NO
#define QW18_SYM_LT KC_TRNS, KC_TRNS, KC_TRNS

#define QW18_SYM_R1 KC_NO, KC_LBRC, KC_RBRC, KC_EXLM, KC_NO
#define QW18_SYM_R2 KC_NO, KC_LPRN, KC_RPRN, KC_QUES, A(KC_SCLN)
#define QW18_SYM_R3 KC_NO, KC_HASH, KC_AT, KC_SCLN, KC_NO
#define QW18_SYM_RT KC_TRNS, LLOCK, KC_TRNS

// ##### Layer NUM

#define QW18_NUM_L1 KC_NO, KC_DLR, A(KC_2), KC_PLUS, KC_NO
#define QW18_NUM_L2 KC_PERC, KC_ASTR, KC_COLN, KC_MINS, KC_NO
#define QW18_NUM_L3 KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
#define QW18_NUM_LT KC_TRNS, KC_TRNS, KC_TRNS

#define QW18_NUM_R1 KC_NO, KC_7, KC_8, KC_9, KC_NO
#define QW18_NUM_R2 KC_0, KC_4, KC_5, KC_6, KC_EQL
#define QW18_NUM_R3 KC_NO, KC_1, KC_2, KC_3, KC_NO
#define QW18_NUM_RT KC_TRNS, LLOCK, KC_TRNS

// ##### Layer 4 EXTENDED
#define QW18_EXT_L1 KC_NO, KC_ESC, KC_MPLY, KC_MNXT, KC_NO
#define QW18_EXT_L2 KC_TAB, LCTL_T(KC_DELETE), LALT_T(KC_PGDN), CW_TOGG, KC_NO
#define QW18_EXT_L3 KC_F18, KC_MUTE, KC_VOLD, KC_VOLU, KC_NO
#define QW18_EXT_LT KC_TRNS, KC_TRNS, KC_SPACE

#define QW18_EXT_R1 KC_NO, KC_CCCV, KC_UP, KC_BSPC, KC_NO
#define QW18_EXT_R2 KC_NO, KC_LEFT, KC_DOWN, KC_RIGHT, KC_ENTER
#define QW18_EXT_R3 KC_NO, KC_BRID, KC_BRIU, KC_NO, KC_NO 
#define QW18_EXT_RT KC_TRNS, LLOCK, KC_TRNS